version: '2'

services:
    web:
        container_name: nginx
        image: nginx:latest
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        container_name: backend
        image: php:fpm
        volumes:
            - ./api:/api
        networks:
            - code-network
        ports:
            - 8080:8080
        command: php -S 0.0.0.0:8080 -t /api
    app:
        container_name: frontend
        build:
            context: ./app/
        command: npm start
        volumes:
            - ./app/:/usr/app
            - /usr/app/node_modules
        ports:
            - "3000:3000"
        networks:
            - code-network
    db:
        image: 'mariadb'
        restart: always
        environment:
            MYSQL_DATABASE: data
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - ./etc/database.sql:/docker-entrypoint-initdb.d/dump.sql
            - db_data:/var/lib/mysql
        networks:
            - code-network
    adminer:
        image: adminer
        restart: always
        ports:
            - '5000:8080'
        environment:
            - PMA_ARBITRARY=1
        networks:
            - code-network
networks:
    code-network:
        driver: bridge

volumes:
    db_data: